name: tests

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.3, 7.4, '8.0', 8.1, 8.2, 8.3, 8.4]
        laravel: [6, 7, 8, 9, 10, 11]
        exclude:
          - php: 7.3
            laravel: 11
          - php: 7.3
            laravel: 9
          - php: 7.3
            laravel: 10
          - php: 7.4
            laravel: 9
          - php: 7.4
            laravel: 10
          - php: 7.4
            laravel: 11
          - php: '8.0'
            laravel: 10
          - php: '8.0'
            laravel: 11
          - php: 8.1
            laravel: 11
          - php: 8.1
            laravel: 6
          - php: 8.1
            laravel: 7
          - php: 8.2
            laravel: 6
          - php: 8.2
            laravel: 7
          - php: 8.2
            laravel: 8
          - php: 8.3
            laravel: 6
          - php: 8.3
            laravel: 7
          - php: 8.3
            laravel: 8
          - php: 8.3
            laravel: 9
          - php: 8.4
            laravel: 6
          - php: 8.4
            laravel: 7
          - php: 8.4
            laravel: 8
          - php: 8.4
            laravel: 9
          - php: 8.4
            laravel: 10

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, soap
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts=^${{ matrix.laravel }}" --dev --prefer-dist --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit
